NorthStorm/Models/Assistants/Grade.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

namespace NorthStorm.Models.Assistants
{
    public class Grade         // جدول الرواتب والدرجات
    {
        #region Model Properties
        public int Id { get; set; }

        [Required(ErrorMessage = "يرجى ادخال الدرجة رقما"),
         Display(Name = "الدرجة رقما")]
        public int GradeNumber { get; set; }

        [StringLength(13, MinimumLength = 4)]
        [Required(ErrorMessage = "يرجى ادخال الدرجة كتابة"),
        Display(Name = "الدرجة كتابة")]
        public string GradeAsWriting { get; set; }

        [Range(170000, 910000)]
        //[DataType(DataType.Currency)]
        //[Column(TypeName = "decimal(11, 3)")]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة الأولى"),
        Display(Name = "المرحلة01")]
        public int Stage01 { get; set; }

        [Range(173000, 930000)]
        //[DataType(DataType.Currency)]
        //[Column(TypeName = "decimal(11, 3)")]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة الثانية"),
        Display(Name = "المرحلة02")]
        public int Stage02 { get; set; }

        [Range(176000, 950000)]
        //[DataType(DataType.Currency)]
        //[Column(TypeName = "decimal(11, 3)")]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة الثالثة"),
        Display(Name = "المرحلة03")]
        public int Stage03 { get; set; }

        [Range(179000, 970000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة الرابعة"),
        Display(Name = "المرحلة04")]
        public int Stage04 { get; set; }

        [Range(182000, 990000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة الخامسة"),
         Display(Name = "المرحلة05")]
        public int Stage05 { get; set; }

        [Range(185000, 1010000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة السادسىة"),
            Display(Name = "المرحلة06")]
        public int Stage06 { get; set; }

        [Range(188000, 1030000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة السابعة"),
        Display(Name = "المرحلة07")]
        public int Stage07 { get; set; }

        [Range(191000, 1050000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة الثامنة"),
        Display(Name = "المرحلة08")]
        public int Stage08 { get; set; }

        [Range(194000, 1070000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة التاسعة"),
         Display(Name = "المرحلة09")]
        public int Stage09 { get; set; }

        [Range(197000, 1090000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة العاشرة"),
         Display(Name = "المرحلة10")]
        public int Stage10 { get; set; }

        [Range(200000, 1110000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ المرحلة الحادية عشر"),
            Display(Name = "المرحلة11")]
        public int Stage11 { get; set; }

        [Range(3000, 20000)]
        [Required(ErrorMessage = "يرجى ادخال مبلغ العلاوة السنوية"),
         Display(Name = " العلاوة السنوية")]
        public int AnnualBonus { get; set; }

        //	[Range(0, 9)]
        [Required(ErrorMessage = "يرجى ادخال المدة الاصغرية للترقية"),
        Display(Name = "مدة الترقية")]
        public int MinimumDuration { get; set; }



        #endregion

        #region Navigstion Properties
        //public ICollection<Employee> Employees { get; set; }
        #endregion
    }
}

NorthStorm/Controllers/GradesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NorthStorm.Data;
using NorthStorm.Interfaces;
using NorthStorm.Models.Assistants;
using NorthStorm.Models.ViewModels;
using NorthStorm.Repositories;
using NorthStorm.ViewModels;

namespace NorthStorm.Controllers
{
    public class GradesController : Controller
    {
        private readonly NorthStormContext _context;
        private readonly IGrade _GradeRepo;

        public GradesController(NorthStormContext context, IGrade gradeRepo)
        {
            _context = context;
            _GradeRepo = gradeRepo;
        }

        // GET: Grades
        public async Task<IActionResult> Index(
            string sortExpression = "",
            string SearchText = "",
            int pg = 1,
            int pageSize = 10)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("Id");
            sortModel.AddColumn("GradeNumber");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            ViewData["pageSize"] = pageSize;

            ViewBag.SearchText = SearchText;

            PaginatedList<Grade> items = await _GradeRepo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pg, pageSize);

            var pager = new PagerModel(items.TotalRecords, pg, pageSize);

            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;

            TempData["CurrentPage"] = pg;
            return View(items);

        }

        // GET: Grades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _GradeRepo.GetItem((int)id);

            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // GET: Grades/Create
        public IActionResult Create()
        {
             
            return View();
        }

        // POST: Grades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GradeNumber,GradeAsWriting,Stage01, Stage02, Stage03, Stage04, Stage05, Stage06, Stage07, Stage08, Stage09, Stage10, Stage11, AnnualBonus, MinimumDuration ")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                bool IsCreated = false;
                string errMessage = "";

                try
                {
                    IsCreated = await _GradeRepo.Create(grade);
                }
                catch (Exception ex)
                {
                    errMessage = errMessage + " " + ex.Message;
                }

                if (IsCreated == false)
                {
                    errMessage = errMessage + " " + _GradeRepo.GetErrors();

                    TempData["ErrorMessage"] = errMessage;
                    ModelState.AddModelError("GradesCreate_POST", errMessage);

                    return View(grade);
                }
                else
                {
                    TempData["SuccessMessage"] = "تمت إضافة القيد " + grade.GradeNumber + " بنجاح.";
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                TempData["ErrorMessage"] = "تأكد من صحة البيانات المدخلة";
                return View(grade);
            }
        }

        // GET: Grades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _GradeRepo.GetItem((int)id);

            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GradeNumber,GradeAsWriting,Stage01, Stage02, Stage03, Stage04, Stage05, Stage06, Stage07, Stage08, Stage09, Stage10, Stage11, AnnualBonus, MinimumDuration ")] Grade grade)
        {
#warning use DbUpdateException \ DbUpdateConcurrencyException and other exceptions for all catches

            if (id != grade.Id)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                bool IsEdited = false;
                string errMessage = "";
                try
                {
                    IsEdited = await _GradeRepo.Edit(grade);
                }
                catch (Exception ex)
                {
                    errMessage = errMessage + " " + ex.Message;
                }

                if (IsEdited == false)
                {
                    errMessage = errMessage + " " + _GradeRepo.GetErrors();

                    TempData["ErrorMessage"] = errMessage;
                    ModelState.AddModelError("GradesEdit_POST", errMessage);

                    return View(grade);
                }
                else
                {
                    TempData["SuccessMessage"] = "تم تحديث القيد " + grade.GradeNumber + " بنجاح";
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                TempData["ErrorMessage"] = "البيانات المدخلة غير صالحة";

                return View(grade);
            }
        }

        // GET: Grades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _GradeRepo.GetItem((int)id);

            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Grade grade)
        {
            bool IsDeleted = false;
            string errMessage = "";
            string gradeInfo = grade.GradeNumber.ToString();

            try
            {
                IsDeleted = await _GradeRepo.Delete(grade);
            }
            catch (Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
            }

            if (IsDeleted == false)
            {
                errMessage = errMessage + " " + _GradeRepo.GetErrors();

                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("GradesDelete_POST", errMessage);
                return View(grade);
            }
            else
            {
                TempData["SuccessMessage"] = "تم حذف القيد " + gradeInfo + " بنجاح";
                return RedirectToAction(nameof(Index));
            }
        }

    }
}

NorthStorm/Views/Grades/Create.cshtml
@model NorthStorm.Models.Assistants.Grade

@{
	ViewData["Title"] = "إنشاء قيد";
}

<h3>@ViewData["Title"]</h3>
<hr />


<div class="card bg-light mb-3">
	<div class="card-header">بيانات القيد</div>
	<form asp-action="Create" class="card-body">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<input type="hidden" asp-for="Id" />
		<div class="row col-md-12">
			<div class="form-group col-md-2">
				<label asp-for="GradeNumber" class="control-label"></label>
				<input asp-for="GradeNumber" class="form-control" />
				<span asp-validation-for="GradeNumber" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="GradeAsWriting" class="control-label"></label>
				<input asp-for="GradeAsWriting" class="form-control" />
				<span asp-validation-for="GradeAsWriting" class="text-danger"></span>
			</div>
		</div>
		<div class="row col-md-12">
			<div class="form-group col-md-2">
				<label asp-for="Stage01" class="control-label"></label>
				<input asp-for="Stage01" class="form-control" />
				<span asp-validation-for="Stage01" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage02" class="control-label"></label>
				<input asp-for="Stage02" class="form-control" />
				<span asp-validation-for="Stage02" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage03" class="control-label"></label>
				<input asp-for="Stage03" class="form-control" />
				<span asp-validation-for="Stage03" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage04" class="control-label"></label>
				<input asp-for="Stage04" class="form-control" />
				<span asp-validation-for="Stage04" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage05" class="control-label"></label>
				<input asp-for="Stage05" class="form-control" />
				<span asp-validation-for="Stage05" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage06" class="control-label"></label>
				<input asp-for="Stage06" class="form-control" />
				<span asp-validation-for="Stage06" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage07" class="control-label"></label>
				<input asp-for="Stage07" class="form-control" />
				<span asp-validation-for="Stage07" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage08" class="control-label"></label>
				<input asp-for="Stage08" class="form-control" />
				<span asp-validation-for="Stage08" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage09" class="control-label"></label>
				<input asp-for="Stage09" class="form-control" />
				<span asp-validation-for="Stage09" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage10" class="control-label"></label>
				<input asp-for="Stage10" class="form-control" />
				<span asp-validation-for="Stage10" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="Stage11" class="control-label"></label>
				<input asp-for="Stage11" class="form-control" />
				<span asp-validation-for="Stage11" class="text-danger"></span>
			</div>

		</div>
		<div class="row col-md-12">
			<div class="form-group col-md-2">
				<label asp-for="AnnualBonus" class="control-label"></label>
				<input asp-for="AnnualBonus" class="form-control" />
				<span asp-validation-for="AnnualBonus" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
				<label asp-for="MinimumDuration" class="control-label"></label>
				<input asp-for="MinimumDuration" class="form-control" />
				<span asp-validation-for="MinimumDuration" class="text-danger"></span>
			</div>
			<div class="form-group col-md-2">
			</div>
			<div class="form-group col-md-2">
			</div>
			<div class="form-group col-md-2">
			</div>
			<div class="form-group col-md-2 align-self-end text-md-center">
				<input type="submit" value="حفظ" class="btn btn-primary w-75" />
			</div>
		</div>
	</form>
	<div class="card-footer">
		<br />

	</div>
</div>

<div>
	<a asp-action="Index">إلغاء</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");

	}
}

NorthStorm/Views/Grades/Index.cshtml
@model IEnumerable<NorthStorm.Models.Assistants.Grade>

@using NorthStorm.Models.ViewModels;

@{
	ViewData["Title"] = "جدول الدرجات والرواتب (دينار عراقي)";
	SortModel sortModel = (SortModel)ViewData["sortModel"];
	PagerModel pager = ViewBag.Pager;
}


<h3>@ViewData["Title"]</h3>
<hr />

<p dir="ltr">
	<a asp-controller="Grades" asp-action="Create" class="h5">إنشاء قيد</a>
</p>

<div class="card bg-light mb-3">
	<div class="card-header">
		<partial name="_topBar" model="@pager" />
	</div>
	<table class="table card-body">
		<thead>
			<tr>
				<th>
					<i class="@sortModel.GetColumn("Id").SortIcon" arial-hidden="true"></i>
					<a asp-action="Index"
					   asp-route-sortExpression="@sortModel.GetColumn("Id").SortExpression"
					   asp-route-pg="@pager.CurrentPage"
					   asp-route-pageSize="@pager.PageSize"
					   asp-route-SearchText="@ViewData["SearchText"]">
						@Html.DisplayNameFor(model => model.Id)
					</a>
				</th>
				<th>
					<i class="@sortModel.GetColumn("GradeNumber").SortIcon" arial-hidden="true"></i>
					<a asp-action="Index"
					   asp-route-sortExpression="@sortModel.GetColumn("GradeNumber").SortExpression"
					   asp-route-pg="@pager.CurrentPage"
					   asp-route-pageSize="@pager.PageSize"
					   asp-route-SearchText="@ViewData["SearchText"]">
						@Html.DisplayNameFor(model => model.GradeNumber)
					</a>
				</th>
				<th>
					@Html.DisplayNameFor(model => model.GradeAsWriting)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage01)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage02)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage03)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage04)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage05)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage06)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage07)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage08)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage09)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage10)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Stage11)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.AnnualBonus)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.MinimumDuration)
				</th>
				<th>
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr class="">
					<td>
						@Html.DisplayFor(modelItem => item.Id)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.GradeNumber)
					</td>
										<td>
						@Html.DisplayFor(modelItem => item.GradeAsWriting)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage01)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage02)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage03)
					</td>
										<td>
						@Html.DisplayFor(modelItem => item.Stage04)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage05)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage06)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage07)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage08)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage09)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage10)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Stage11)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.AnnualBonus)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.MinimumDuration)
					</td>
					<td>
						<a asp-action="Details" asp-route-id="@item.Id">
							<span class="btn btn-sm btn-outline-primary">
								<i class="fa fa-eye" aria-hidden="true" data-bs-toggle="tooltip" data-bs-placement="top" title="عرض التفاصيل"></i>
							</span>
						</a>

						<a asp-action="Edit" asp-route-id="@item.Id">
							<span class="btn btn-sm btn-outline-warning">
								<i class="fa fa-edit" aria-hidden="true" data-bs-toggle="tooltip" data-bs-placement="top" title="تعديل القيد"></i>
							</span>
						</a>

						<a asp-action="Delete" asp-route-id="@item.Id" class="text-danger">
							<span class="btn btn-sm btn-outline-danger">
								<i class="fa fa-trash" aria-hidden="true" data-bs-toggle="tooltip" data-bs-placement="top" title="حذف القيد"></i>
							</span>
						</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
	<div class="card-footer" style="height:50px">
		<partial name="_bottomBar" model="@pager" />
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}